line_length:
  warning: 140
  ignores_comments: true
  ignores_interpolated_strings: true
colon:
  flexible_right_spacing: true
type_name:
  allowed_symbols: "_"
  min_length: 1
identifier_name:
  allowed_symbols: "_"
  min_length: 1
switch_case_alignment:
  indented_cases: true
function_parameter_count: 8
file_length: 1600
type_body_length: 400
large_tuple: 4
cyclomatic_complexity:
  warning: 15
  ignores_case_statements: true
function_body_length: 100
trailing_comma:
  mandatory_comma: true
nesting:
  type_level: 2
statement_position:
  statement_mode: uncuddled_else
disabled_rules:
  - todo                # TODOs are permitted as annotated markers for future improvements.
  - closure_parameter_position # We allow starting closure parameter lists on the next line when long or preceded by capture declarations.
  - type_body_length    # https://github.com/realm/SwiftLint/issues/4631
