variables:
  JEKYLL_ENV: production
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build_project:
  stage: build
  script:
    - "( brew install libsodium json-c )"
    - "( ./lib/bin/build_libsodium-macos )"
    - "( cd ./platform-independent/cli-c && ./clean && targets='mpw mpw-bench mpw-tests' ./build && ./mpw-tests && ./mpw-cli-tests )"
    - "( cd ./gradle && ./gradlew --info clean test )"
    - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword iOS' -sdk iphonesimulator clean build )"
    - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword macOS' clean build )"
  tags:
    - brew
    - java
    - xcode_9
  only:
    - master

pages:
  stage: deploy
  script:
    - exec jekyll build -d public
  artifacts:
    paths:
      - public
  tags:
    - jekyll
  only:
    - gh-pages
