variables:
  JEKYLL_ENV: production
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build_project:
  stage: build
  script:
    - "( ./lib/bin/build_libsodium-macos )"
    - "( cd ./platform-independent/cli-c && ./clean && targets='mpw mpw-bench mpw-tests' ./build && ./mpw-tests && ./mpw-cli-tests )"
    - "( cd ./gradle && ./gradlew --info clean test )"
    - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword iOS' -sdk iphonesimulator clean build )"
    - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword macOS' clean build )"
  tags:
    - xcode-9
  only:
    - master

pages:
  stage: build
  script:
  - exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - gh-pages
